server:
  port: 8881
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
# 创建activiti数据库
  activiti:
    # 自动部署：false（不允许自动部署）
    check-process-definitions: false
    db-history-used: true
    history-level: full
    # 默认值已经变成true了
    database-schema-update: true

#    mail-server-host: 
#    mail-server-port: 
#    mail-server-default-from: 
#    mail-server-user-name:
#    mail-server-password:
#    mail-server-use-ssl: 
  security:
    user:
      name: user
      password: password
#  thymeleaf:
#    mode: HTML
#    encoding: utf-8
#    # 禁用缓存
#    cache: false
