## 此文件中的配置都是全局配置
server:
  port: ${SERVER_PORT:8801}
  servlet:
    session:
      cookie:
        ## 为0则不提供cookie，所以每次请求都需要验证
        max-age: 0

spring:
  profiles:
    # 使用application-mysql.yml
    active: mysql
    # 包含application-mysql.yml
    include: mysql
  # 创建activiti数据库
  activiti:
    # 自动部署：false（不允许自动部署）
    check-process-definitions: false
    db-history-used: true
    history-level: full
    # 默认值已经变成true了
    database-schema-update: true

#    mail-server-host: 
#    mail-server-port: 
#    mail-server-default-from: 
#    mail-server-user-name:
#    mail-server-password:
#    mail-server-use-ssl: 
  security:
    user:
      name: username
      password: password
      roles: ADMIN
#  thymeleaf:
#    mode: HTML
#    encoding: utf-8
#    # 禁用缓存
#    cache: false
